name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install libxcb-dependencies
      run: sudo apt-get install -y libxcb-keysyms1
    - name: add mising library symlink
      run: sudo ln -s /usr/lib/x86_64-linux-gnu/libxcb-keysyms.so.1 /usr/lib/x86_64-linux-gnu/libxcb-keysyms.so
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
